name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Authenticate with Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@main
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # Deploy to Cloud Run
    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy hello-world-service --image=docker.io/hashicorp/http-echo:latest --region=europe-west1 --platform=managed --allow-unauthenticated