name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Revoke all previous gcloud authentications
    - name: Revoke previous gcloud authentications
      run: gcloud auth revoke --all || true

    # Authenticate with Google Cloud using Workload Identity Federation
    - id: auth
      name: Authenticate to Google Cloud with WIF
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: "projects/red-delight-393913/locations/global/workloadIdentityPools/github/providers/github-provider"
        service_account: "github-cloud-run@red-delight-393913.iam.gserviceaccount.com"
        create_credentials_file: 'true'

    # Set up Cloud SDK
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    # Deploy to Google Cloud Run
    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy hello-world-service --image=docker.io/mendhak/http-https-echo:latest --region=europe-west1 --platform=managed --allow-unauthenticated
