name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: red-delight-393913
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to Cloud Run
      run: |
        # Authenticate docker to gcloud
        gcloud auth configure-docker

        # Build and push the image to Google Container Registry
        docker pull hello-world:latest
        docker tag hello-world:latest gcr.io/your-gcp-project-id/hello-world
        docker push gcr.io/your-gcp-project-id/hello-world

        # Deploy the image to Cloud Run
        gcloud run deploy hello-world-service --image gcr.io/your-gcp-project-id/hello-world --platform managed --region us-central1 --allow-unauthenticated
