name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@main
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
      
    - name: Deploy to Cloud Run
      run: |
        # Authenticate docker to gcloud
        gcloud auth configure-docker

        # Build and push the image to Google Container Registry
        docker pull hello-world:latest
        docker tag hello-world:latest gcr.io/red-delight-393913/hello-world
        docker push gcr.io/red-delight-393913/hello-world

        # Deploy the image to Cloud Run
        gcloud run deploy hello-world-service --image gcr.io/red-delight-393913/hello-world --platform managed --region europe-west1 --allow-unauthenticated
