name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Authenticate with Google Cloud using Workload Identity Federation
    - name: Authenticate to Google Cloud with WIF
      uses: google-github-actions/auth@main
      with:
        workload_identity_pool_id: "github"
        workload_identity_provider_id: "github-provider"
        service_account_id: "github-cloud-run@red-delight-393913.iam.gserviceaccount.com"
        # The location of your service account's key. You can store it as a GitHub secret.
        private_key_id: ${{ secrets.GCP_PRIVATE_KEY_ID }}
        private_key: ${{ secrets.GCP_PRIVATE_KEY }}
        project_id: "red-delight-393913"
        # Use the following token_lifetime if needed; by default, it's one hour
        token_lifetime: "3600s"

    # Deploy to Cloud Run
    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy hello-world-service --image=docker.io/mendhak/http-https-echo:latest --region=europe-west1 --platform=managed --allow-unauthenticated
