name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    # Authenticate with Google Cloud using Workload Identity Federation
    - name: Authenticate to Google Cloud with WIF
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/1023774981113/locations/global/workloadIdentityPools/github/providers/github-provider
        service_account: github-cloud-run@red-delight-393913.iam.gserviceaccount.com
    - id: deploy
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: hello-world-service
        image: docker.io/mendhak/http-https-echo:latest
        region: europe-west1
    - name: Use output
      env:
        URL: ${{ steps.deploy.outputs.url }}
      run: curl "$URL"