name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Revoke all previous gcloud authentications
    - name: Revoke previous gcloud authentications
      run: gcloud auth revoke --all || true

    # Authenticate with Google Cloud using Workload Identity Federation
    - id: auth
      name: Authenticate to Google Cloud with WIF
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: "projects/1023774981113/locations/global/workloadIdentityPools/github/providers/github-provider"
        service_account: "github-cloud-run@red-delight-393913.iam.gserviceaccount.com"
        create_credentials_file: 'true'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: 'hello-world-service'
        image: 'docker.io/mendhak/http-https-echo:latest'
    - name: 'Use output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'