name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Authenticate with Google Cloud using Workload Identity Federation
    - id: auth
      name: Authenticate to Google Cloud with WIF
      uses: google-github-actions/auth@main
      with:
        workload_identity_provider: "projects/red-delight-393913/locations/global/workloadIdentityPools/github/providers/github-provider"
        service_account: "github-cloud-run@red-delight-393913.iam.gserviceaccount.com"
        create_credentials_file: 'true'
        activate_credentials: 'true'
        # The location of your service account's key. You can store it as a GitHub secret.
        private_key_id: ${{ secrets.GCP_PRIVATE_KEY_ID }}
        private_key: ${{ secrets.GCP_PRIVATE_KEY }}
        project_id: "red-delight-393913"
        # Use the following token_lifetime if needed; by default, it's one hour
        token_lifetime: "3600s"
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud auth activate-service-account --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud config set project red-delight-393913
      # Deploy to Cloud Run
    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy hello-world-service --image=docker.io/mendhak/http-https-echo:latest --region=europe-west1 --platform=managed --allow-unauthenticated
