name: Terraform FMT Check

on:
  push:
  pull_request:

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform FMT
      run: terraform fmt -check -recursive
